### ISSUE TITLE
[Question] On the motion estimation module in SVT-AV1. 

### ISSUE THREAD

**Issue by Somdyuti2** [AOMediaCodec/SVT-AV1#1474] opened 2020-09-04 18:30 UTC
Hi, I am trying to understand the motion estimation module of SVT-AV1 by studying the code and the associated documentation provided. I have a few questions regarding some parts which were not immediately apparent to me as follows:

1. From the documentation, I understand that SVT-AV1 uses hierarchical motion estimation (HME) to compute an initial search center of  a superblock (SB) and then a refinement step to compute the integer pel MVs of each PU within a SB before the fractional pel refinement step. My first question is how are the MVs stored after the integer full search step, and how many MVs are stored for each SB and each reference picture? There is a data structure defined as `p_sb_best_full_pel_mv[MAX_NUM_OF_REF_PIC_LIST][MAX_REF_IDX][MAX_ME_PU_COUNT]` in _SVT-AV1/Source/Lib/Encoder/Codec/EbMotionEstimationContext.h,_ but I am not sure if this is the one which holds the MVs of each PU within a SB, as it seemed to be containing only 0 values when I checked with the debugger, and also there are no x and y (horizontal and vertical) components of the MVs within this data structure. Could you please point me to the appropriate data structure that holds the integer MVs of each PUs of each SB after the function  `motion_estimate_sb(...) ` is called in _SVT-AV1/Source/Lib/Encoder/Codec/EbTemporalFiltering.c_ before the sub-pel refinement step?

2. According to **Figure 11: Search center select and motion estimation**. and **Figure 12: Motion estimation dataflow**.of _SVT-AV1/Docs/svt-av1-encoder-design.md_, there are 1101 or 4421 MVs. Could you please clarify what these numbers (1101 or 4421) represent in this context and how were they derived? It is not apparent to me since there should not be that many PUs for each SB, and also it does not mention that the numbers are for each SB in the first place. 

3. After finding the MVs of each PU, we are also interested in computing the residuals frames for each PU size and reference picture For example, by compensating the entire current picture with blocks of size 16x16 for a particular reference, we can get one residual for 16x16 blocks and so on. Is this feasible? Also, it seems that the numbering of the references with respect to the current frame is relative. Is it possible to get the actual reference numbers in terms of POCs?

It will be helpful if someone can offer some clarifications on the above questions. Thanks for your help.

**Comment by ttrigui** [comment] 2020-09-10 21:41
Hi @Somdyuti2 please fin below my answers. I hope that it helps.

> 1. From the documentation, I understand that SVT-AV1 uses hierarchical motion estimation (HME) to compute an initial search center of  a superblock (SB) and then a refinement step to compute the integer pel MVs of each PU within a SB before the fractional pel refinement step. My first question is how are the MVs stored after the integer full search step, and how many MVs are stored for each SB and each reference picture? There is a data structure defined as `p_sb_best_full_pel_mv[MAX_NUM_OF_REF_PIC_LIST][MAX_REF_IDX][MAX_ME_PU_COUNT]` in _SVT-AV1/Source/Lib/Encoder/Codec/EbMotionEstimationContext.h,_ but I am not sure if this is the one which holds the MVs of each PU within a SB, as it seemed to be containing only 0 values when I checked with the debugger, and also there are no x and y (horizontal and vertical) components of the MVs within this data structure. Could you please point me to the appropriate data structure that holds the integer MVs of each PUs of each SB after the function  `motion_estimate_sb(...) ` is called in _SVT-AV1/Source/Lib/Encoder/Codec/EbTemporalFiltering.c_ before the sub-pel refinement step?

- The array we use to store the MVs is p_sb_best_mv[MAX_NUM_OF_REF_PIC_LIST][MAX_REF_IDX][SQUARE_PU_COUNT]. The xMV and yMV can be extracted using _MVXT() and _MVYT() as follows: _MVXT(context_ptr->p_sb_best_mv[list_index][ref_pic_index][n_idx])

> 2. According to **Figure 11: Search center select and motion estimation**. and **Figure 12: Motion estimation dataflow**.of _SVT-AV1/Docs/svt-av1-encoder-design.md_, there are 1101 or 4421 MVs. Could you please clarify what these numbers (1101 or 4421) represent in this context and how were they derived? It is not apparent to me since there should not be that many PUs for each SB, and also it does not mention that the numbers are for each SB in the first place.

- 1101 is the maximum number of blocks per SB when SB size is 64x64 and 4421 is the maximum number of blocks per SB when SB size is 128x128. Theoretically, we should have that much MVs if we chose to do ME for all block sizes. However by design we chose to do ME for square blocks only which is why the number of MVs is much less. 

> 3. After finding the MVs of each PU, we are also interested in computing the residuals frames for each PU size and reference picture For example, by compensating the entire current picture with blocks of size 16x16 for a particular reference, we can get one residual for 16x16 blocks and so on. Is this feasible? Also, it seems that the numbering of the references with respect to the current frame is relative. Is it possible to get the actual reference numbers in terms of POCs?

- Would you please be able to clarify a little more your question? Do you want to know if we have the POC number of the reference picture rather than the delta relative to the current one?

**Comment by Somdyuti2** [comment] 2020-09-13 02:14
Hi, thanks for the answers. They are definitely helpful and I could find the MVs in the way you suggested. I think I would like to get a few things clarified though.

1.  So, the default SB size for ME is 64x64 (according to a comment in _Source/API/EbSvtAv1Enc.h_ and hence the number of square PUs that each SB can have is 85 (`SQUARE_PU_COUNT`), and MVs are computed for each of these. However, the `width` and `height` fields of `sb_geom` are set to 128, and I am guessing that the SB size in mode decision (MD) is different from that in ME. So. if a 128x128 PU/block is chosen in the MD step, would its MVs be found by some form of interpolation step? Is it the same case (i.e. MV interpolation) for non-square PUs/blocks? I observed that there are some functions pertaining to ME in the MD process; for example in _SVT-AV1/Source/Lib/Encoder/Codec/EbModeDecision.c_  a function called `single_motion_search(...)` calls another function named _eb_av1_obmc_full_pixel_search(..)_ which is defined in _SVT-AV1/Source/Lib/Encoder/Codec/av1me.c_, and the purpose of these full search steps at this point were not clear to me. Might it be possible that they are handling the MV interpolation steps for the block sizes chosen during SB partitioning? 

2. Does the data structure  `p_sb_best_mv[MAX_NUM_OF_REF_PIC_LIST][MAX_REF_IDX][SQUARE_PU_COUNT]` hold the MVs from the largest to smallest blocks in the SB the scan order? i.e. for each reference picture, index 0 holds MV for the 64x64 block, inidces 1-4 hold the MVs of the four 32x32 blocks in the SB from starting from the top left corner and so on? 

3. Let me try to elaborate the third point of my original post:

- Having a way to map the delta positions of the reference pictures to actual POC numbers would be useful, so that is definitely one thing I want to know, although it seems that it may not always be possible to do that as some references might be ALTREFs etc. If such a mapping has not already been implemented, then would it still be possible to do it using the POC of the current picture (most probably given by `pcs_ptr->picture_number`) and the delta values (the numbers in `pcs_ptr->pred_struct_ptr->pred_struct_entry_ptr_array->ref_list0->reference_list` and `pcs_ptr->pred_struct_ptr->pred_struct_entry_ptr_array->ref_list1->reference_list`)? There is also a field called `pcs_ptr->ref_pic_poc_array`,  whose name suggests that it might hold some information relevant to this, but it seems to be having only 0 values, so I am not sure. 

-  Also, is there a one to one correspondence between these delta reference numbers and the order in which the MVs are stored in `p_sb_best_mv` For example, do the MVs in `p_sb_best_mv[0]1][:]` say, correspond to those that are computed with respect to the second reference in list0 whose corresponding delta position is given by `picture_control_set_ptr_central->pred_struct_ptr->pred_struct_entry_ptr_array->ref_list0->reference_list[1]`?

- If there is such an one to one correspondence as described in the previous point, then we can extract the MVs and associate them with the POCs of the references using the delta reference numbers held in `pred_struct_ptr`, and the POC of the current picture being encoded. However, some references are pruned during ME, and it seems we can check if a reference was pruned by checking the flag `context_ptr->hme_results[list_index][ref_pic_index].do_ref`. My understanding is that if a reference is pruned at the HME step, there will be no associated MVs for that reference (again, not entirely sure, so please let me know if otherwise).  All that being said,  there is still a possibility that some of the references are ALTREFs and thereby has no correspondence in the original source. How to identify if a set of MVs corresponds to an actual source frame or an ALTREF?

Thanks for your help with this, and could you please let me know about the above stuff? I might also have some questions on the prediction structure, so I wanted to ask if it will be appropriate to post here or if I might have to open another "Question" issue for it.

**Comment by ttrigui** [comment] 2020-09-14 22:49
> Hi, @Somdyuti2 I'm glad that my previous answers helped.
Please find below my reply.

> 1. So, the default SB size for ME is 64x64 (according to a comment in _Source/API/EbSvtAv1Enc.h_ and hence the number of square PUs that each SB can have is 85 (`SQUARE_PU_COUNT`), and MVs are computed for each of these. However, the `width` and `height` fields of `sb_geom` are set to 128, and I am guessing that the SB size in mode decision (MD) is different from that in ME. So. if a 128x128 PU/block is chosen in the MD step, would its MVs be found by some form of interpolation step? Is it the same case (i.e. MV interpolation) for non-square PUs/blocks? I observed that there are some functions pertaining to ME in the MD process; for example in _SVT-AV1/Source/Lib/Encoder/Codec/EbModeDecision.c_  a function called `single_motion_search(...)` calls another function named _eb_av1_obmc_full_pixel_search(..)_ which is defined in _SVT-AV1/Source/Lib/Encoder/Codec/av1me.c_, and the purpose of these full search steps at this point were not clear to me. Might it be possible that they are handling the MV interpolation steps for the block sizes chosen during SB partitioning?

- When a 128x128 block is processed we use the MV of the corresponding 64x64 upper left block. For nsq PUs we actually do full search in MD md_nsq_motion_search() based on sq MVs which are used as MV center.  single_motion_search() this motion search is only done for OBMC which also uses ME MVs to derive other MVs for OBMC.

> 2. Does the data structure  `p_sb_best_mv[MAX_NUM_OF_REF_PIC_LIST][MAX_REF_IDX][SQUARE_PU_COUNT]` hold the MVs from the largest to smallest blocks in the SB the scan order? i.e. for each reference picture, index 0 holds MV for the 64x64 block, inidces 1-4 hold the MVs of the four 32x32 blocks in the SB from starting from the top left corner and so on?

- Correct. Please refer to EbMeTierZeroPu .

> 3. Let me try to elaborate the third point of my original post:
> 
> * Having a way to map the delta positions of the reference pictures to actual POC numbers would be useful, so that is definitely one thing I want to know, although it seems that it may not always be possible to do that as some references might be ALTREFs etc. If such a mapping has not already been implemented, then would it still be possible to do it using the POC of the current picture (most probably given by `pcs_ptr->picture_number`) and the delta values (the numbers in `pcs_ptr->pred_struct_ptr->pred_struct_entry_ptr_array->ref_list0->reference_list` and `pcs_ptr->pred_struct_ptr->pred_struct_entry_ptr_array->ref_list1->reference_list`)? There is also a field called `pcs_ptr->ref_pic_poc_array`,  whose name suggests that it might hold some information relevant to this, but it seems to be having only 0 values, so I am not sure.

-  pcs_ptr->ref_pic_poc_array[list_index][ref_pic_index] holds the POC values of reference frames.

> * Also, is there a one to one correspondence between these delta reference numbers and the order in which the MVs are stored in `p_sb_best_mv` For example, do the MVs in `p_sb_best_mv[0]1][:]` say, correspond to those that are computed with respect to the second reference in list0 whose corresponding delta position is given by `picture_control_set_ptr_central->pred_struct_ptr->pred_struct_entry_ptr_array->ref_list0->reference_list[1]`?

- Not directly. context_ptr->p_sb_best_mv[list_index][ref_pic_index][n_idx] and pcs_ptr->ref_pic_poc_array[list_index][ref_pic_index] share list_index which can be 0 and 1 and ref_pic_index which can be up to the number of reference.

> * If there is such an one to one correspondence as described in the previous point, then we can extract the MVs and associate them with the POCs of the references using the delta reference numbers held in `pred_struct_ptr`, and the POC of the current picture being encoded. However, some references are pruned during ME, and it seems we can check if a reference was pruned by checking the flag `context_ptr->hme_results[list_index][ref_pic_index].do_ref`. My understanding is that if a reference is pruned at the HME step, there will be no associated MVs for that reference (again, not entirely sure, so please let me know if otherwise).  All that being said,  there is still a possibility that some of the references are ALTREFs and thereby has no correspondence in the original source. How to identify if a set of MVs corresponds to an actual source frame or an ALTREF?
> 

- I'm unfortunately not too knowledgeable about the details of handling reference pictures but If you need more clarifications/details, just give us some time and either myself or @hassount will get back to you on this.

> Thanks for your help with this, and could you please let me know about the above stuff? I might also have some questions on the prediction structure, so I wanted to ask if it will be appropriate to post here or if I might have to open another "Question" issue for it.

- I suggest that you open another issue if you have questions about a different topic.

**Comment by Somdyuti2** [comment] 2020-09-16 20:49
@ttrigui  thank you for the clarifications. It is fine if one of you could look into my last question about the reference pictures whenever you can later on, and let me know.

**Comment by Somdyuti2** [comment] 2020-10-02 16:49
Hi, could I ask for a couple of further clarifications regarding the MVs that are computed by the ` motion_estimate_sb()` function? 

- I extracted the MVs using `_MVXT()` and `_MVYT()` as you suggested for a few different test sequences and different `--preset` settings. However, in all cases, some MVs seem to be having a unusually large magnitudes, that are even larger than the frame dimensions for all presets and video inputs.  For example, for a 1080p video, I observed that the magnitude some MVs were above 3000 at preset 1, which does not make any sense to me. Is this normal, or is there an error somewhere? If it is the expected behavior, what is the explanation for such large MVs?

- It looks like the magnitude of the integer Mvs are always multiples of 4 . I saw a comment or two like `Constrain x_ME to be a multiple of 8 (round up)`, but I was not able to interpret it, and also, I got the MVs in both directions to be multiples of 4. Could you please let me know what is the reason for this choice?  It might be related to the downsampling in the HME step, but I am not sure, and seems like this is reducing the precision of MVs. I thought that the integer full search step should be able to generate MVs at the pixel level precision. 

@ttrigui  or @hassount It would be helpful if you could clarify these two points. Thanks for your help thus far.

**Comment by silverbacknet** [comment] 2020-10-03 06:22
The full-pel estimation process will output 4x scaled up vectors because they have to be used with the quarter-pel interpolated image that they'll be refined in, or simply output as-is for the ; after refinement at higher levels, you should see final MVs that aren't a multiple of 4. Likewise, I believe if 8th-pel interpolation is used, full-pel will be in multiples of 8, though I'm not familiar with that aspect.

That also explains why the MVs are over 3000 even for 1920x1080; they're actually being applied to a 7680x4320 plane. Although extending out that distance still seems unusual and unlikely to be worth testing, but you never really know what's globally more compact. If it's not a win they'll be pruned in the refinement.

**Comment by Somdyuti2** [comment] 2020-10-05 02:31
@silverbacknet thank you that makes sense.

**Comment by silverbacknet** [comment] 2020-10-05 13:06
Those are the actual MVs that will be placed into the bitstream, and it's also far easier to reason about all output always coming out in the scale of the reference picture the decoder will need to use, not "well sometimes it's in fullpel, sometimes it's in qpel, depending on if we've run refinement yet..."

If you want to consider them in the context of the input picture, I do think you should implement a step in your analysis output that reduces them by the reference picture scaling factor (1x, 4x, or 8x). 1x comes into play when you have an I-frame or in screen-coding scenarios, btw.

**Comment by silverbacknet** [comment] 2020-10-05 13:16
`--pred-me` is roughly similar in concept to `--subme` in x264, if that helps. To completely turn subpel refinement off, you just need `--pred-me 1`.

**Comment by ttrigui** [comment] 2020-10-06 16:24
> The full-pel estimation process will output 4x scaled up vectors because they have to be used with the quarter-pel interpolated image that they'll be refined in, or simply output as-is if refinement isn't chosen; after refinement at higher levels, you should see final MVs that aren't a multiple of 4. Likewise, I believe if 8th-pel interpolation is used, full-pel will be in multiples of 8, though I'm not familiar with that aspect.
> 
> That also explains why the MVs are over 3000 even for 1920x1080; they're actually being applied to a 7680x4320 plane. Although extending out that distance still seems unusual and unlikely to be worth testing, but you never really know what's globally more compact. If it's not a win they'll be pruned in the refinement.

Correct The MVs are scaled up. It depends on the precision. If allow_high_precision_mv you have to divide MVs by 8 otherwise you divide by 4.

**Comment by Somdyuti2** [comment] 2020-10-06 16:27
Thanks @silverbacknet  and @ttrigui  for taking the time to explain this.

**Comment by hassount** [comment] 2020-10-06 16:57
Great, thank you all, @Somdyuti2 can we then close this issue ?

**Comment by Somdyuti2** [comment] 2020-10-06 17:23
@hassount I had a query about the correspondence between the computed MVs and their reference frames from earlier, which was not fully answered at that point, and @ttrigui suggested that it could be clarified later. That is why I had not closed the issue myself. Based on the information that I have gathered so far I am rephrasing the remaining question below:

> It seemed from the answer given earlier that the reference POC for a set of MVs can be found using the `pcs_ptr->ref_pic_poc_array` However, some references are pruned during HME, and I think we can check if a reference was pruned by checking the flag `context_ptr->hme_results[list_index][ref_pic_index].do_ref`. My understanding is that if a reference is pruned at the HME step, there will be no associated MVs for that reference. Please let me know if that is correct.  Also, I think that some of the references might be ALTREFs and thereby have no correspondence in the original source.  So, is there an entry corresponding to ALTREF references in `pcs_ptr->ref_pic_poc_array` and how to know if a set of MVs came from an actual source frame or an ALTREF?

Please let me know if the above could be answered sometime soon, or feel free to close the issue otherwise.

**Comment by hassount** [comment] 2020-10-06 17:42
@Somdyuti2 great, let me clarify these and close the issue.

>It seemed from the answer given earlier that the reference POC for a set of MVs can be found using the pcs_ptr-ref_pic_poc_array However, some references are pruned during HME, and I think we can check if a reference was pruned by checking the flag context_ptr->hme_results[list_index][ref_pic_index].do_ref. My understanding is that if a reference is pruned at the HME step, there will be no associated MVs for that reference.

Correct. but from an ME point of view but the Mode decision could still use those references though for Nearest Near generation etc.

>Please let me know if that is correct. Also, I think that some of the references might be ALTREFs and thereby have no correspondence in the original source. So, is there an entry corresponding to ALTREF references in pcs_ptr->ref_pic_poc_array and how to know if a set of MVs came from an actual source picture or an ALTREF?

An Altref is like any other reference and would be included in the reference array, the encoder would not know whether it's an ALTREF or a regular picture, it's just a reference.

**Closed by hassount** 2020-10-06 17:42 UTC
Labels: question
