### ISSUE TITLE
[Feature Request] Add more configuration options to the ffmpeg build

### ISSUE THREAD

**Issue by Felixkruemel** [AOMediaCodec/SVT-AV1#1672] opened 2021-01-14 08:22 UTC
The current encoder has a really big set of options you can specify.
https://github.com/AOMediaCodec/SVT-AV1/blob/master/Docs/svt-av1_encoder_user_guide.md 

If just using an ffmpeg build there's nearly no configuration. You are very limited in you can do, to be exact most you can do is specify -rc for VBR, CRF and so on and the preset.

libaomav1 on the other hand has most options already backed into the ffmpeg build which I think is really neat.

This is in some part also linked to https://github.com/AOMediaCodec/SVT-AV1/issues/1555

**Comment by hassount** [comment] 2021-01-16 22:09
@Felixkruemel agreed, this seems to be a duplicate of #1555 , closing this issue.

**Closed by hassount** 2021-01-16 22:09 UTC
Labels: duplicate
